version: "3"

services:
  mongodb:
    image: 'bitnami/mongodb:3.6'
    container_name: mongodb
    labels:
      kompose.service.type: nodeport
    ports:
      - "27017:27017"
    volumes:
      - './mongodata:/bitnami'

  golang:
    build: ./
    container_name: simple-storage
    ports: 
      - "8080:3000"
    volumes:
      - ./buckets:/simplestorage/buckets:rw
      - ./:/simplestorage
    depends_on:
      - mongodb
    links:
      - mongodb
    environment:
      - PROD=DOCKER