version: "3"

services:
  mongodb:
    image: mongo:4.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongodata:/data/db

  golang:
    build: ./
    container_name: simple-storage
    ports: 
      - "8080:3000"
    volumes:
      - ./buckets:/simplestorage/buckets:rw
      - ./:/simplestorage
    depends_on:
      - mongodb
    links:
      - mongodb
    environment:
      - PROD=DOCKER